### ISSUE TITLE
removeDir() does not work on empty folders

### ISSUE THREAD

**Issue by ceab254** [lazzard/php-ftp-client#21]
Hey, when I want to delete an empty dir with $client->removeDir('test'); I get the following error:

[FtpClientException] - Unable to get files list for [test] directory

When I use $client->listDirDetails('test') on an empty folder I also get the same error.

Thanks for the package

**Comment by AmraniCh** [comment]
Hey, thanks for opening this issue.

The issue was fixed in PR #22 and a new version will be released soon! Thank you.
