### ISSUE TITLE
FTPClient->asyncUpload null variable definition issue

### ISSUE THREAD

**Issue by sebyspi** [lazzard/php-ftp-client#27]
Hi, 
this is not a real bug, but I wanted to report it anyway.
I has an annoing issue with PHP intelephense because in FTPClient.php in asyncUpload function at row 972 you have:
`$sizeTmp        = null`

then in the same function at row 984:
`'transferred' => $this->transferredBytes($remoteFileSize, $sizeTmp),`

And the transferredByte definition is:
`protected function transferredBytes(float $size, float $previousSize) : int // row 1282`

I know it's not a real error, but Intelephense considers it as such and this leads to an error chain.

So i change `$sizeTmp = null` with `$sizeTmp = 0.0`.

Could this change made from me leads to an real error if should I use the asyncUpload function?

Best regards and thanks

**Comment by AmraniCh** [comment]
Hey, thanks for opening this issue.

Your change shouldn't raise any error and your code should work just fine, I will consider a PR to fix this issue!
