### ISSUE TITLE
Upload Async method can't find $speed

### ISSUE THREAD

**Issue by jumpingaccess** [lazzard/php-ftp-client#42]
Hi,
I'm testing your FTP Client  and I've just something strange with AsyncUpload, php replies $speed is not define .
have you a example of async upload  ?
thanks

**Comment by jumpingaccess** [comment]
Ok , Seems the call_user_func_array function gives that error with PHP 8.2.

**Comment by AmraniCh** [comment]
Hey, thanks for opening this issue.
The library is not tested yet on PHP version 8.2 (see the 'integration tests workflow [here](https://github.com/lazzard/php-ftp-client/blob/master/.github/workflows/tests.yml)), however, we plan to add support for It as soon as possible.

As a temporary solution, you could extend the FtpClient class and overrides the async method implementation to get rid of the errors on PHP v8.2, thank you!
