### ISSUE TITLE
 Append/Restart not permitted

### ISSUE THREAD

**Issue by MatDepInfo** [lazzard/php-ftp-client#43]
Hello,
When I try to use "copyFromLocal" command, i get this error:  Append/Restart not permitted
I check on the server, the option [AllowStoreRestart] is well to ON
Any idea ?

**Comment by AmraniCh** [comment]
Hey, thanks for opening this issue.
This error typically occurs when an FTP server is not configured to allow file transfer operation, you're right about the directive **AllowStoreRestart** should be ON, but I wonder what you have restarted your FTP server to apply the new configuration ?
