### ISSUE TITLE
Bug in FtpClietn::isExists($remoteFile)

### ISSUE THREAD

**Issue by fortune1dev** [lazzard/php-ftp-client#45]
When `$this->wrapper->nlist(str_replace('\\', '/', dirname($remoteFile)))` return full path to $remoteFile (depend from FTP-server), then 
```
return in_array(
            basename($remoteFile),
            $list
        );
```
allways return FALSE;

**Comment by AmraniCh** [comment]
Hey!

`$this->wrapper->nlist` is just a shortcut for the built in function [`ftp_nlist`](https://www.php.net/manual/en/function.ftp-nlist.php), try doing `$this->wrapper->getErrorMessage` after `$this->wrapper->nlist(str_replace('\\', '/', dirname($remoteFile)))`  and see what error you will get!
