### ISSUE TITLE
How to upload $_File Data or base64 file 

### ISSUE THREAD

**Issue by patelsumit5192** [lazzard/php-ftp-client#46]
Hello sir,
I have uploaded a simple method it's working fine but I want to upload a file using the **`$_File`** variable using your library.
if any method are present then guide me or provided link.

**Comment by AmraniCh** [comment]
Hey.

Of course you can upload a file using $_FILE, just use the library API method `upload()` and specify the local file path that is inside the $_FILE super global, like so:

```php
$uploaddir = '/var/www/uploads/';
$uploadfile = $uploaddir . basename($_FILES['userfile']['name']);

if (move_uploaded_file($_FILES['userfile']['tmp_name'], $uploadfile)) {
    $client->upload($uploadfile, 'path/to/remote/file');
}
```

If you need any help let me know!
